name: Test Project 
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        uses: npm install
      - name: Run Test
        uses: npm run test

